# Generated by Django 2.2.6 on 2019-10-24 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.ManyToManyField(db_table='app_Movie_Genre', to='app_genres.Genre')),
            ],
            options={
                'db_table': 'app_Movie',
                'ordering': ('title',),
            },
        ),
    ]
