# Generated by Django 2.2.6 on 2019-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0003_auto_20191023_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
