sudo: required

language: python

python:
    - "3.6"

env:
    WORKON_HOME=.pipenv/venvs
    PIP_CACHE_DIR=.pipenv/pipcache
    REDIS_DSN=redis://redis.service:6379
    DJENV=Test
    MYSQL_HOST=localhost
    MYSQL_NAME=fsd
    MYSQL_NAME_TEST=fsd_test
    MYSQL_USER=travis
    MYSQL_PASSWORD=

cache:
    directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR

services:
    - mysql
    - redis-server

install:
    - pip install pipenv
    - pipenv install --dev

before_script:
    - pipenv run flake8 .

script:
    - pipenv run coverage run manage.py test --failfast --debug-mode -v 2 app_genres

after_success:
    - coveralls