# Generated by Django 2.2.6 on 2019-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailTemplate',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=10000)),
            ],
            options={
                'db_table': 'app_UserEmailTemplate',
                'ordering': ('id',),
            },
        ),
    ]
